### ISSUE TITLE
channel 타입 체크 시 category id를 넣으면 오류 발생

### ISSUE THREAD

**Issue by comjun04** [comjun04/flashbot#49]
argument run할 때 channel 타입 체크시 category id를 넣으면 UnhandledPromiseRejection 발생

```
(node:25194) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Channel
    at RequestHandler.execute (/data/data/com.termux/files/home/flashbot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/data/data/com.termux/files/home/flashbot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
(node:25194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:25194) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

채널을 찾을 수 없다고 나옴

**Comment by comjun04** [comment]
해결했는데 이슈를 안 닫았네
